### ISSUE TITLE
Globbing works strange in case workdir has files

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#19]
Do a clean test of `list`
```
$ rm -rf *.xlf *.xml
$ smartling-cli files list **test.xml
/files/placeholder_test.xml  2017-06-23T09:37:30Z  xml
/files/test.xml              2017-05-04T17:09:04Z  xml
test.xml                     2017-06-22T15:52:00Z  xml
```
I have 3 files. Now let's download the single file
```
$ smartling-cli files pull *test.xml --source
downloaded test.xml
```
So far so good. Let's get list of files again
```
$ smartling-cli files list **test.xml
test.xml  2017-06-22T15:52:00Z  xml
```
Wow, only single file on remote server?
Ok, let's download all files (3 is expected)
```
$ smartling-cli files pull **test.xml --source
downloaded test.xml
```

Looks like something wrong with globbing

**Comment by seletskiy** [comment]
@dimitrystd: It's not a bug. You need to quote globbing argument, because it's expanded by your shell and when you have on single file inside your directory which matches glob, shell expands it into file name:

Try:
```
ls **test.xml
```

You need to quote argument to achieve correct behavior:

```
smartling-cli files list '**test.xml'
```

https://github.com/Smartling/smartling-cli/tree/v2#upload-files-by-mask

**Comment by dimitrystd** [comment]
Thanks, my bad, missed in documentation.
