### ISSUE TITLE
Use full template for generating config file

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#22]
I configured tool and decided to add more configuration
```
$ cat smartling.yml
user_id: my-user-id
secret: my-secret
account_id: accountuid
project_id: projectid
threads: 4
files: {}
```
Unfortunately i don't see any comments and examples. So if i the average user then i will not try to find online documentation or review source code.

Would be nice if we can copy and update our [template](https://github.com/Smartling/smartling-cli/blob/v2/smartling.yml.example).

**Comment by seletskiy** [comment]
@dimitrystd: Unfortunately, it's not so easy to implement, because current implementation of `init` will preserve any configuration fields that are already present in config file, e.g. if user changes something in config file and then run `init` again, that change will be preserved.

So, essentially, there are two choices:

* do not preserve contents of config file and overwrite it with default template every time `init` is executed;
* do not preserve comments in config file, but preserve values entered by user.

**Comment by dimitrystd** [comment]
I vote for the 1st option (don't preserve content). It was cool to see existing data and just hit enter. But it's `init` command, not `setup` or `update` which supposed to preserve data.

**Comment by seletskiy** [comment]
@dimitrystd: fixed.
