### ISSUE TITLE
Incomplete Download with CLI

### ISSUE THREAD

**Issue by a-zhigalov** [Smartling/smartling-cli#64]
When downloading a large number of files via CLI for 20 languages this [file](https://dashboard.smartling.com/app/projects/3c208b44f/files/list.html#file/en_resx%5CFiles%5CAE%5CDataAccess%5CProperties%5CErrors.resx) would often download: 

- _fully_ only for the first handful of languages 
- only _partially_ for the subsequent language and 
- _not download at all_ for the remaining languages. 

This has happened multiple times over the past several months. Download would most of the time stop at 3rd or 4th language. 

It would be great if a permanent solution could be implemented to avoid a workaround every time we have to deliver this project to Devs.

**Comment by dimitrystd** [comment]
Would be nice to see the error that CLI writes in console. I suspect it was a timeout error in CLI because File API response may take longer than 60sec.

CLI configuration was updated and new version v1.3 is released. [Updated](https://github.com/Smartling/smartling-cli/wiki/Installation) your CLI and try again. You can use `smartling-cli --version` for checking your current version.

**Comment by a-zhigalov** [comment]
Thanks. FYI this was the error (not necessarily always on that language though):
* 2019-07-01 13:05:29   [ERROR] unable to write file contents into "ja-JP\en_resx\Files\AE\DataAccess\Properties\Errors.resx"
                                └─ net/http: request canceled (Client.Timeout exceeded while reading body)

**Comment by dimitrystd** [comment]
Thanks for the confirmation. That's exactly what was fixed.
